const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
class Node{constructor(tag){this.tag=tag;this.children=[];this.dataset={};this.attrs={};this.value=''}append(...x){this.children.push(...x)}replaceChildren(...x){this.children=x}add(x){this.append(x)}setAttribute(k,v){this.attrs[k]=v}}
const nodes={},opened=[];let enabled=true;
const field={rankThresholds:[{tier:'ノーマル',level:1,energy:0},{tier:'ノーマル',level:2,energy:1000},{tier:'スーパー',level:1,energy:5000}],encounters:[{sleepStyleId:'1_01',rank:{tier:'ノーマル',level:1},drowsyPower:123},{sleepStyleId:'1_02',rank:{tier:'ノーマル',level:2},drowsyPower:null,eventOnly:true},{sleepStyleId:'2_01',rank:{tier:'ノーマル',level:2},drowsyPower:456}]};
const context={document:{getElementById:id=>nodes[id]??=new Node(),createElement:tag=>new Node(tag)},Option:function(text,value){this.textContent=text;this.value=value},window:{PS_CATALOG:{pokemon:{1:{no:1,name:'フシギダネ',faceImage:'face1.png'},2:{no:2,name:'フシギソウ',image:'body2.png'}},sleepStyles:{1:[{id:'1_01',stars:1,name:'ねむり'},{id:'1_02',stars:2,name:'ねむり2'}],2:[{id:'2_01',stars:null,name:'未確認寝顔'}]}},PS_UI_ART:{rank:()=>{}},PS_DEX_ROUTE:{url:key=>'pokemon.html?species='+key},PS_IMAGE_LOADING:{set:(img,src,kind)=>{assert.equal(kind,'pokemon');if(enabled)img.src=src;else img.dataset.manualSrc=src}},openPokemonDetail:no=>opened.push(no)}};
vm.createContext(context);const core=fs.readFileSync('templates/fields/03-details.html','utf8')+'function selectField(){}';vm.runInContext(core.slice(core.indexOf('function renderFieldEncounters('),core.indexOf('function selectField(')),context);context.renderFieldEncounters(field);
const sections=nodes.fieldEncounterList.children;assert.equal(sections.length,3);assert.equal(sections[1].children[0].children[1].textContent,'1,000');assert.equal(sections[2].children.length,1);
const first=sections[0].children[1].children[0],second=sections[1].children[1].children[0],unknown=sections[1].children[1].children[1];assert.equal(first.dataset.sleepStyleId,'1_01');assert.equal(first.children[1].textContent,'★1');assert.equal(second.children[1].textContent,'★2');assert.equal(unknown.children[1].textContent,'★未確認');assert(second.title.includes('未確認・イベント条件あり'));assert.equal(first.href,'pokemon.html?species=0001_default');assert.equal(first.children[0].children[0].loading,'lazy');first.onclick({preventDefault(){}});assert.deepEqual(opened,[1]);assert.equal(nodes.fieldEncounterCount.textContent,'3 / 3 件の収録済み寝顔');
nodes.fieldRankFilter.value='ノーマル:1';context.renderFieldEncounters(field);assert.equal(nodes.fieldEncounterList.children.length,1);assert.equal(nodes.fieldEncounterCount.textContent,'1 / 3 件の収録済み寝顔');enabled=false;context.renderFieldEncounters(field);const img=nodes.fieldEncounterList.children[0].children[1].children[0].children[0].children[0];assert.equal(img.src,undefined);assert.equal(img.dataset.manualSrc,'face1.png');
console.log('Rank energy headings, exact unlock grouping, stars, unknown values, cutoff filtering, lazy/manual faces and detail links passed');
