const assert=require('node:assert/strict'),vm=require('node:vm');
const ctx={};vm.createContext(ctx);vm.runInContext(require('./daily_kernel.cjs'),ctx);
const m=(berry,fieldId,effect)=>ctx.dailyExModifiers({berry},{fieldId,effect,berries:['main','sub','third']});
assert.equal(m('main','greengrass_ex','berry').speed,.9);
assert.equal(m('other','greengrass_ex','berry').speed,1.15);
assert.equal(m('main','cyan_ex','skill').speed,.8);
assert.equal(m('other','cyan_ex','skill').speed,1.35);
assert.equal(m('sub','cyan_ex','skill').skillChance,1.25);
assert.equal(m('other','cyan_ex','skill').skillChance,1);
assert.equal(m('main','greengrass_ex','berry').favoriteFactor,2.4);
assert.equal(m('sub','greengrass_ex','ingredients').ingredients,1);
assert.equal(m('main','greengrass','ingredients').ingredients,0);
assert.equal(m('main','cyan_ex','skill').skillLevel,1);
console.log('EX main/sub/nonfavorite, weekly effects and normal isolation passed.');
ctx.team=['one'];ctx.state={box:[{id:'one',no:1,name:'one',level:1,skillLevel:1}]};
ctx.window={PS_CATALOG:{pokemon:{1:{ingredientSlots:[{unlock:1,candidates:[{name:'food',qty:2}]}],berry:'main',specialty:'食材',mainSkillId:'s'}},berries:{main:30,sub:30,third:30},skills:{s:{maxLevel:2,name:'s',effectType:'fixed_energy',levels:{1:{energy:10},2:{energy:20}}}}}};
ctx.teamSpeedContext=()=>({members:new Map([['one',{speed:3600,carry:10000,food:50,berryQty:1,skill:10,energyFactor:1}]])});
const run=effect=>ctx.dailyBaseline(ctx.team,ctx.state.box,ctx.window.PS_CATALOG,4,0,false,false,['main','sub','third'],0,{},undefined,{},effect?{fieldId:'greengrass_ex',berries:['main','sub','third'],effect}:null);
const normal=run(null),berry=run('berry'),food=run('ingredients'),skill=run('skill');
assert.equal(normal.members[0].normalHelps,24);assert.equal(berry.members[0].normalHelps,26,'86400 / 3240 seconds: 26 completed helps');
assert(Math.abs(berry.berryEnergy/normal.berryEnergy-1.2*26/24)<1e-8);
assert(Math.abs(food.foods.get('food')/normal.foods.get('food')-1.5*26/24)<1e-8);
assert.equal(berry.members[0].skillLevel,2);assert(skill.members[0].skillTriggers>berry.members[0].skillTriggers);
assert.equal(ctx.state.box[0].skillLevel,1);
assert(run(null).berryEnergy===normal.berryEnergy);
console.log('EX production, food yields, energy, skill caps, probability and Box preservation passed.');
