const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.join(__dirname,'..');
const catalog={berries:{berry:30},pokemon:{1:{berry:'berry',ingredientSlots:[{unlock:1,candidates:[{name:'same',qty:1}]},{unlock:30,candidates:[{name:'same',qty:1}]}]}}};
const item={id:'one',no:1,name:'Test',level:30,nature:'まじめ',subskills:['known','known']};
let speed=3600,food=50;
const ctx={Map,Set,Number,Math,SUBSKILL_LEVELS:[10,25,50,70,80],speciesFor:item=>catalog.pokemon[item.no],teamSpeedContext:()=>({members:new Map([['one',{speed,food,berryQty:1,unknown:[]}]])}),berryEnergyAtLevel:()=>30};
vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(root,'templates/whistle/01-calculator.html'),'utf8'),ctx);
const estimate=(options={})=>ctx.whistleEstimate(['one'],[item],catalog,options);
const close=(a,b)=>assert(Math.abs(a-b)<1e-9,`${a} != ${b}`);
let r=estimate();close(r.foods.get('same'),10/3);close(r.berryCount,10/3);close(r.berryEnergy,100);
r=estimate({favoriteBerries:['berry'],areaBonus:50});close(r.berryEnergy,300);
// Expected quantities remain unrounded for one, two and three slots.
catalog.pokemon[1].ingredientSlots.pop();r=estimate();close(r.foods.get('same'),10/3);
catalog.pokemon[1].ingredientSlots.push({unlock:30,candidates:[{name:'second',qty:4}]},{unlock:60,candidates:[{name:'third',qty:6}]});
item.level=60;item.subskills.push('known');r=estimate();close(r.foods.get('same'),10/9);close(r.foods.get('second'),40/9);close(r.foods.get('third'),20/3);
// Current energy, collection, camp, meal and skill fields never enter this route.
assert.deepEqual(estimate({goodCamp:true,initialEnergy:0,collectionHours:8}),estimate({goodCamp:false,initialEnergy:150,collectionHours:1}));
speed=1800;assert(estimate().berryCount>r.berryCount,'uses team-corrected time');speed=3600;
r=estimate({favoritesKnown:false});assert.equal(r.berryEnergy,null);assert(r.foods.size>0);
food=null;r=estimate();assert(r.pendingReasons.length);assert.equal(r.berryCount,null);assert.equal(r.berryEnergy,null);assert.equal(r.foods.size,0);food=50;
item.nature=null;assert(estimate().pendingReasons.length);assert.equal(estimate({assumeNeutral:true}).pendingReasons.length,0);item.nature='まじめ';
item.ingredients={};catalog.pokemon[1].ingredientSlots[1].candidates.push({name:'alternative',qty:3});assert(estimate({assumeNeutral:true}).pendingReasons.length);catalog.pokemon[1].ingredientSlots[1].candidates.pop();
catalog.pokemon[1].dailyCalculationStatus='pending_special_skill';assert(estimate().pendingReasons.length);delete catalog.pokemon[1].dailyCalculationStatus;
assert(estimate({fieldMode:'ex'}).pendingReasons.length);assert(ctx.whistleEstimate(['missing'],[item],catalog).pendingReasons.length);
console.log('Whistle: unrounded aggregation, one/two/three slots, field energy, independent inputs and unknown-condition hold passed.');
const rows=JSON.parse(fs.readFileSync(path.join(root,'master/research/field-spawn-counts.json'))).fields;
vm.runInContext(fs.readFileSync(path.join(root,'templates/fields/01-spawn-calculator.html'),'utf8'),ctx);
assert.equal(Object.values(rows).flat().length,45);assert.equal(Object.values(rows).flat().filter(r=>r.exactThreshold!==null).length,12);
assert.equal(ctx.spawnEnergyBounds(rows.greengrass[4],100).estimate,195636);assert.equal(ctx.spawnEnergyBounds(rows.greengrass[4],50).estimate,391272);
assert.equal(ctx.spawnEnergyBounds(rows.cyan_ex[2],100).lower,null);assert.equal(ctx.spawnEnergyBounds(rows.amber[4],100).estimate,976396);assert.equal(ctx.spawnEnergyBounds(rows.amber[4],100).upper,976659);
assert.equal(ctx.spawnEnergyBounds(rows.greengrass[0],0),null);assert.equal(ctx.spawnEnergyBounds(rows.greengrass[0],101),null);
console.log('Spawn data: 45 rows, 12 exact observations, score conversion, Amber conflict and unknown Cyan EX lower bound preserved.');
