const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
class N{constructor(tag){this.tagName=tag.toUpperCase();this.events={};this.children=[];this.textContent='';this.value=''}append(...nodes){this.children.push(...nodes);if(this.tagName==='SELECT'&&!this.value)this.value=nodes[0].value}replaceChildren(){this.children=[]}setAttribute(){}addEventListener(type,fn){this.events[type]=fn}get childElementCount(){return this.children.length}}
const hosts={};const document={createElement:t=>new N(t),getElementById:id=>hosts[id]??=new N('div')};const c={window:{PS_PAGE_RENDERERS:{},PS_NUMBERS:{display:n=>Number(n).toFixed(1)}},document};vm.createContext(c);const h=fs.readFileSync('review.html','utf8');const scripts=[...h.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g)].map(m=>m[1]);for(const s of scripts)new vm.Script(s);vm.runInContext(scripts.find(s=>s.includes('window.PS_RANK_CONDITIONS=')),c);vm.runInContext(scripts.find(s=>s.includes('window.PS_TRIAL_RANKINGS=')),c);const d=c.window.PS_TRIAL_RANKINGS;assert.equal(d.energy.types.length,18);assert.equal(d.energy.islands.length,6);assert.equal(d.food.groups.length,19);assert(d.energy.overallTop.some(x=>x.teammateProductionDeltaPerDay<0));for(const g of d.energy.types)for(const x of g.entries)assert(Math.abs(x.energyPerHour*24-x.ownBerryPerDay-x.skillEnergyPerDay-x.teammateProductionDeltaPerDay)<1e-6);c.window.PS_PAGE_RENDERERS.skillEnergyRankingPage();c.window.PS_PAGE_RENDERERS.ingredientRankingPage();c.window.PS_RENDER_FIELD_TRIAL('cyan');function walk(n){return [n,...n.children.flatMap(walk)]}function openAll(host){for(const n of walk(host)){if(n.tagName==='DETAILS'){n.open=true;n.events.toggle?.()}}}assert.equal(walk(hosts.ingredientRankingContent).filter(n=>n.tagName==='TABLE').length,0);openAll(hosts.skillEnergyRankingContent);openAll(hosts.fieldRankingContent);const nodes=walk(hosts.ingredientRankingContent),select=nodes.find(n=>n.tagName==='SELECT');select.value='normalTop5';select.onchange();openAll(hosts.ingredientRankingContent);assert.equal(walk(hosts.ingredientRankingContent).filter(n=>n.tagName==='TABLE').length,19);select.value='skillTop5';select.onchange();openAll(hosts.ingredientRankingContent);assert.equal(walk(hosts.ingredientRankingContent).filter(n=>n.tagName==='TABLE').length,19);select.value='foodSpecialtyTop5';select.onchange();openAll(hosts.ingredientRankingContent);assert.equal(walk(hosts.ingredientRankingContent).filter(n=>n.tagName==='TABLE').length,19);assert.equal(walk(hosts.fieldRankingContent).filter(n=>n.tagName==='TABLE').length,1);console.log('Trial rankings: 18 types, 6 islands, 19 foods, all selectors, negative contribution and decomposition passed');
vm.runInContext(scripts.find(s=>s.includes('window.PS_BERRY_RANKINGS=')),c);
c.window.PS_PAGE_RENDERERS.islandRankingPage();
const islandSelect=walk(hosts.islandRankingContent).find(n=>n.tagName==='SELECT');assert.equal(islandSelect.children.length,9);assert.equal(islandSelect.value,'cyan');const originalField=hosts.fieldRankingContent.children;
for(const id of ['cyan','taupe','snowdrop','lapis','old_gold','amber']){islandSelect.value=id;islandSelect.onchange();openAll(hosts.islandRankingContent);assert.equal(walk(hosts.islandRankingContent).filter(n=>n.tagName==='TABLE').length,2);assert.equal(hosts.fieldRankingContent.children,originalField)}
for(const id of ['greengrass','greengrass_ex','cyan_ex']){islandSelect.value=id;islandSelect.onchange();assert.equal(walk(hosts.islandRankingContent).filter(n=>n.tagName==='TABLE').length,0)}
assert.equal(d.metadata.configurations,1970);const egg=d.food.groups.find(g=>g.ingredient==='とくせんエッグ');for(const mode of ['normalTop5','skillTop5','foodSpecialtyTop5']){assert.equal(egg[mode][4].name,'モロバレル');assert.equal(egg[mode][4].pattern,'ABB');assert.equal(egg[mode][4].rank,5)}
const info=h.match(/<section id="info"[\s\S]*?<\/section>/)[0],ranking=h.match(/<section id="rankingPage"[\s\S]*?<\/section>/)[0];assert(info.includes('data-info-page="rankingPage"'));for(const page of ['typeRankingPage','islandRankingPage','skillEnergyRankingPage','ingredientRankingPage']){assert(ranking.includes(`data-info-page="${page}"`));assert(!info.includes(`data-info-page="${page}"`))}
for(const no of ['0590','0591']){const m=JSON.parse(fs.readFileSync(`master/pokemon/${no}/data.json`));assert.equal(m.rateStatus,'推定');assert(m.skillRate>0&&m.foodRate>0);assert.equal(m.sleepNameReferences.length,4);assert(m.sleepNameReferences.every(r=>r.sleepStyleId===null&&r.image===null&&r.requiredDrowsyPower===null));assert.equal(m.sleepStyles.length,0)}
console.log('Ranking hub, independent island selector, egg correction, estimated rates and no fabricated sleep IDs passed');

const bookshelf=h.match(/<section id="bookshelfPage"[\s\S]*?<\/section>/)[0];assert(bookshelf.includes('EXフィールドの参考予想'));assert.equal((h.match(/<summary>EXフィールドの参考予想<\/summary>/g)||[]).length,1);
