const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const ctx={window:{},structuredClone,console};vm.createContext(ctx);
vm.runInContext(read('vendor/enigma-special/special_skill_kernel.mjs').replace(/\bexport /g,'')+'\nconst tables='+read('vendor/enigma-special/effect_tables.json')+';window.PS_SPECIAL_ENGINE={kernel:createKernel(tables),tables,ingredientNames:{coffee:"coffee"},initialState,provisionalCountDistribution};',ctx);
vm.runInContext(require('./daily_kernel.cjs'),ctx);
vm.runInContext(read('templates/core/02-team.html').split('function normalizeTeam')[0]+read('templates/team/07-swap-comparison.html'),ctx);
ctx.box=Array.from({length:7},(_,i)=>({id:'m'+i,no:i+1,name:'member'+i,level:1,skillLevel:6}));
ctx.catalog={pokemon:Object.fromEntries(ctx.box.map((x,i)=>[x.no,{no:x.no,type:'ノーマル',berry:'berry',specialty:'スキル',mainSkillId:i===6?'healing_pulse_energy_cheer_s':'normal',ingredientSlots:[{unlock:1,candidates:[{name:i===0?'tomato':'coffee',qty:2}]}]}])),berries:{berry:10},skills:{normal:{id:'normal',name:'normal',effectType:'fixed_energy',maxLevel:1,levels:{1:{energy:100}}},healing_pulse_energy_cheer_s:{id:'healing_pulse_energy_cheer_s',name:'healing',effectType:'reference_only',maxLevel:6,levels:{6:{}}}}};
ctx.teamSpeedContext=ids=>({members:new Map(ids.map(id=>[id,{speed:ids.includes('m5')?3000:3600,carry:20,food:50,berryQty:1,skill:id==='m6'?100:0,energyFactor:1}]))});
ctx.request={ids:['m0','m1','m2','m3','m4'],box:ctx.box,catalog:ctx.catalog,interval:2,energy:30,camp:false,meals:3,favorites:['berry'],areaBonus:80,zones:{},pot:{skill:0},energies:{m5:150,m6:30},demand:{coffee:300,tomato:20}};
const snapshot=JSON.stringify(ctx.request);
const before=vm.runInContext('dailySwapForecast(request)',ctx);assert(!before.missing);ctx.before=before;
ctx.ids=['m5','m1','m2','m3','m4'];const after=vm.runInContext('dailySwapForecast(request,ids)',ctx);ctx.after=after;assert(!after.missing);
const diff=vm.runInContext('dailySwapDifference(before,after,request.demand)',ctx);
assert(diff.foods.coffee.delta>0);assert(diff.foods.tomato.delta<0);assert.equal(diff.foods.tomato.expected,0);assert.equal(diff.foods.tomato.deficit,20);
assert(after.members.find(m=>m.id==='m1').normalHelps>before.members.find(m=>m.id==='m1').normalHelps,'Remaining allies must use the new team bonus');
const direct=vm.runInContext('dailyBaseline(ids,request.box,request.catalog,request.interval,request.energy,request.camp,request.meals,request.favorites,request.areaBonus,request.zones,request.pot,request.energies)',ctx);assert.equal(after.foods.get('coffee'),direct.foods.get('coffee'));
ctx.ids=['m6','m1','m2','m3','m4'];const healing=vm.runInContext('dailySwapForecast(request,ids)',ctx);assert(healing.members.some(m=>m.specialRecoveryNet>0));
ctx.request.camp=true;const camp=vm.runInContext('dailySwapForecast(request)',ctx);assert(camp.foods.get('coffee')>before.foods.get('coffee'));ctx.request.camp=false;
ctx.request.energies.m5=0;ctx.ids=['m5','m1','m2','m3','m4'];const low=vm.runInContext('dailySwapForecast(request,ids)',ctx);assert(low.members[0].normalHelps<after.members[0].normalHelps);ctx.request.energies.m5=150;
assert(vm.runInContext('dailySwapForecast(request,["m0","m0","m2","m3","m4"]).missing',ctx));
ctx.catalog.pokemon[6].specialTeamLimited=true;ctx.catalog.pokemon[7].specialTeamLimited=true;
assert.equal(vm.runInContext('dailySwapCompatible(["m5","m6","m2","m3","m4"],box,catalog)',ctx),false);
delete ctx.catalog.pokemon[6].specialTeamLimited;delete ctx.catalog.pokemon[7].specialTeamLimited;
ctx.catalog.pokemon[6].ingredientSlots=[];assert(vm.runInContext('dailySwapForecast(request,["m5","m1","m2","m3","m4"]).missing',ctx));ctx.catalog.pokemon[6].ingredientSlots=[{unlock:1,candidates:[{name:'coffee',qty:2}]}];
assert.equal(JSON.stringify(ctx.request),snapshot,'No input, saved team, pot or Box mutation');
const ui=read('templates/team/05-swap-assist.html');assert(!ui.includes('supplementTiming('));assert(ui.includes('controller.signal.aborted'));assert(ui.includes('setTimeout(resolve,0)'));assert(ui.includes('options.slice(0,10)'));assert(ui.includes("mode!=='normal'"));
console.log('Swap comparison: shared five-member forecast, ally bonus/recovery, outgoing food loss, camp, individual energies, composition limits, incomplete inputs, no mutation and cancellable UI passed.');
